package com.romm.android.utils

/**
 * Maps RomM platform slugs to ES-DE (EmulationStation Desktop Edition) folder names
 */
object PlatformMapper {

    private val rommToEsdeMapping = mapOf(
        "3do" to "3do",
        "abc-80" to "abc-80",
        "acorn-archimedes" to "archimedes",
        "acorn-electron" to "electron",
        "acpc" to "amstradcpc",
        "action-max" to "action-max",
        "advanced-pico-beena" to "advanced-pico-beena",
        "adventure-vision" to "adventure-vision",
        "airconsole" to "airconsole",
        "alice-3290" to "alice-3290",
        "altair-680" to "altair-680",
        "altair-8800" to "altair-8800",
        "amazon-alexa" to "amazon-alexa",
        "amazon-fire-tv" to "amazon-fire-tv",
        "amiga" to "amiga",
        "amiga-cd" to "amiga",
        "amiga-cd32" to "amigacd32",
        "amstrad-gx4000" to "gx4000",
        "amstrad-pcw" to "amstrad-pcw",
        "analogueelectronics" to "analogueelectronics",
        "android" to "androidgames",
        "antstream" to "antstream",
        "apf" to "apf",
        "apple" to "apple",
        "apple-iigs" to "apple2gs",
        "apple-lisa" to "apple-lisa",
        "apple-pippin" to "apple-pippin",
        "appleii" to "apple2",
        "appleiii" to "appleiii",
        "1292-advanced-programmable-video-system" to "1292-advanced-programmable-video-system",
        "aquarius" to "aquarius",
        "arcade" to "arcade",
        "arcadia-2001" to "arcadia",
        "arduboy" to "arduboy",
        "astral-2000" to "astral-2000",
        "astrocade" to "astrocde",
        "atari-jaguar-cd" to "atarijaguarcd",
        "atari-st" to "atarist",
        "atari-vcs" to "atari-vcs",
        "atari-xegs" to "atarixe",
        "atari2600" to "atari2600",
        "atari5200" to "atari5200",
        "atari7800" to "atari7800",
        "atari800" to "atari800",
        "atari8bit" to "atari800",
        "atmos" to "atmos",
        "atom" to "atom",
        "ay-3-8500" to "ay-3-8500",
        "ay-3-8603" to "ay-3-8603",
        "ay-3-8605" to "ay-3-8605",
        "ay-3-8606" to "ay-3-8606",
        "ay-3-8607" to "ay-3-8607",
        "ay-3-8610" to "ay-3-8610",
        "ay-3-8710" to "ay-3-8710",
        "ay-3-8760" to "ay-3-8760",
        "bada" to "bada",
        "bbcmicro" to "bbcmicro",
        "beena" to "beena",
        "beos" to "beos",
        "bit-90" to "bit-90",
        "bk" to "bk",
        "bk-01" to "bk-01",
        "black-point" to "black-point",
        "blackberry" to "blackberry",
        "blacknut" to "blacknut",
        "blu-ray-player" to "blu-ray-player",
        "brew" to "brew",
        "browser" to "browser",
        "bubble" to "bubble",
        "c-plus-4" to "plus4",
        "c128" to "c128",
        "c16" to "c16",
        "c64" to "c64",
        "call-a-computer" to "call-a-computer",
        "camputers-lynx" to "camputers-lynx",
        "casio-cfx-9850" to "casio-cfx-9850",
        "casio-fp-1000" to "casio-fp-1000",
        "casio-loopy" to "casio-loopy",
        "casio-pb-1000" to "casio-pb-1000",
        "casio-programmable-calculator" to "casio-programmable-calculator",
        "casio-pv-1000" to "pv1000",
        "casio-pv-2000" to "casio-pv-2000",
        "cdccyber70" to "cdccyber70",
        "champion-2711" to "champion-2711",
        "clickstart" to "clickstart",
        "colecoadam" to "adam",
        "colecovision" to "colecovision",
        "colour-genie" to "colour-genie",
        "commander-x16" to "commander-x16",
        "commodore-cdtv" to "cdtv",
        "compal-80" to "compal-80",
        "compucolor-i" to "compucolor-i",
        "compucolor-ii" to "compucolor-ii",
        "compucorp-programmable-calculator" to "compucorp-programmable-calculator",
        "cpet" to "cpet",
        "cpm" to "cpm",
        "creativision" to "crvision",
        "cybervision" to "cybervision",
        "danger-os" to "danger-os",
        "daydream" to "daydream",
        "dc" to "dreamcast",
        "dedicated-console" to "dedicated-console",
        "dedicated-handheld" to "dedicated-handheld",
        "didj" to "didj",
        "digiblast" to "digiblast",
        "doja" to "doja",
        "donner30" to "donner30",
        "dos" to "dos",
        "dragon-32-slash-64" to "dragon32",
        "dvd-player" to "dvd-player",
        "e-reader-slash-card-e-reader" to "e-reader-slash-card-e-reader",
        "ecd-micromind" to "ecd-micromind",
        "edsac" to "edsac",
        "elektor" to "elektor",
        "enterprise" to "enterprise",
        "epoch-cassette-vision" to "epoch-cassette-vision",
        "epoch-game-pocket-computer" to "epoch-game-pocket-computer",
        "epoch-super-cassette-vision" to "scv",
        "evercade" to "evercade",
        "excalibur-64" to "excalibur-64",
        "exelvision" to "exelvision",
        "exen" to "exen",
        "exidy-sorcerer" to "exidy-sorcerer",
        "fairchild-channel-f" to "channelf",
        "famicom" to "famicom",
        "fds" to "fds",
        "fm-7" to "fm7",
        "fm-towns" to "fmtowns",
        "fred-cosmac" to "fred-cosmac",
        "freebox" to "freebox",
        "g-and-w" to "gameandwatch",
        "g-cluster" to "g-cluster",
        "galaksija" to "galaksija",
        "gamate" to "gamate",
        "game-dot-com" to "gamecom",
        "game-wave" to "game-wave",
        "gamegear" to "gamegear",
        "gamestick" to "gamestick",
        "gb" to "gb",
        "gba" to "gba",
        "gbc" to "gbc",
        "gear-vr" to "gear-vr",
        "genesis" to "genesis",
        "gimini" to "gimini",
        "gizmondo" to "gizmondo",
        "gloud" to "gloud",
        "glulx" to "glulx",
        "gnex" to "gnex",
        "gp2x" to "gp2x",
        "gp2x-wiz" to "gp2x-wiz",
        "gp32" to "gp32",
        "gt40" to "gt40",
        "gvm" to "gvm",
        "handheld-electronic-lcd" to "handheld-electronic-lcd",
        "hartung" to "gmaster",
        "hd-dvd-player" to "hd-dvd-player",
        "heathkit-h11" to "heathkit-h11",
        "heathzenith" to "heathzenith",
        "hikaru" to "hikaru",
        "hitachi-s1" to "hitachi-s1",
        "hp-9800" to "hp-9800",
        "hp-programmable-calculator" to "hp-programmable-calculator",
        "hp2100" to "hp2100",
        "hp3000" to "hp3000",
        "hrx" to "hrx",
        "hugo" to "hugo",
        "hyper-neo-geo-64" to "hyper-neo-geo-64",
        "hyperscan" to "hyperscan",
        "ibm-5100" to "ibm-5100",
        "ideal-computer" to "ideal-computer",
        "iircade" to "iircade",
        "imlac-pds1" to "imlac-pds1",
        "intel-8008" to "intel-8008",
        "intel-8080" to "intel-8080",
        "intel-8086" to "intel-8086",
        "intellivision" to "intellivision",
        "intellivision-amico" to "intellivision-amico",
        "interact-model-one" to "interact-model-one",
        "interton-vc-4000" to "interton-vc-4000",
        "interton-video-2000" to "interton-video-2000",
        "ios" to "ios",
        "ipad" to "ipad",
        "ipod-classic" to "ipod-classic",
        "j2me" to "j2me",
        "jaguar" to "atarijaguar",
        "jolt" to "jolt",
        "jupiter-ace" to "jupiter-ace",
        "kaios" to "kaios",
        "kim-1" to "kim-1",
        "kindle" to "kindle",
        "laser200" to "laser200",
        "laseractive" to "laseractive",
        "leapfrog-explorer" to "leapfrog-explorer",
        "leapster" to "leapster",
        "leapster-explorer-slash-leadpad-explorer" to "leapster",
        "leaptv" to "leaptv",
        "legacy-computer" to "legacy-computer",
        "linux" to "linux",
        "luna" to "luna",
        "lynx" to "atarilynx",
        "mac" to "macintosh",
        "maemo" to "maemo",
        "mainframe" to "mainframe",
        "matsushitapanasonic-jr" to "matsushitapanasonic-jr",
        "meego" to "meego",
        "mega-duck-slash-cougar-boy" to "megaduck",
        "memotech-mtx" to "memotech-mtx",
        "meritum" to "meritum",
        "meta-quest-2" to "meta-quest-2",
        "meta-quest-3" to "meta-quest-3",
        "microbee" to "microbee",
        "microcomputer" to "microcomputer",
        "microtan-65" to "microtan-65",
        "microvision" to "microvision",
        "mobile" to "mobile",
        "mobile-custom" to "mobile-custom",
        "model1" to "model1",
        "model2" to "model2",
        "model3" to "model3",
        "mophun" to "mophun",
        "mos-technology-6502" to "mos-technology-6502",
        "motorola-6800" to "motorola-6800",
        "motorola-68k" to "motorola-68k",
        "mre" to "mre",
        "msx" to "msx1",
        "msx-turbo" to "msxturbor",
        "msx2" to "msx2",
        "msx2plus" to "msx2",
        "mtx512" to "mtx512",
        "mugen" to "mugen",
        "multivision" to "multivision",
        "3ds" to "n3ds",
        "n64" to "n64",
        "64dd" to "n64dd",
        "nascom" to "nascom",
        "nds" to "nds",
        "nec-pc-6000-series" to "nec-pc-6000-series",
        "neo-geo-cd" to "neogeocd",
        "neo-geo-pocket" to "ngp",
        "neo-geo-pocket-color" to "ngpc",
        "neo-geo-x" to "neo-geo-x",
        "neogeoaes" to "neogeo",
        "neogeomvs" to "neogeo",
        "nes" to "nes",
        "new-nintendo-3ds" to "n3ds",
        "newbrain" to "newbrain",
        "newton" to "newton",
        "ngage" to "ngage",
        "ngage2" to "ngage",
        "ngc" to "gc",
        "nimrod" to "nimrod",
        "nintendo-dsi" to "nds",
        "northstar" to "northstar",
        "noval-760" to "noval-760",
        "nuon" to "nuon",
        "oculus-go" to "oculus-go",
        "oculus-quest" to "oculus-quest",
        "oculus-rift" to "oculus-rift",
        "oculus-vr" to "oculus-vr",
        "odyssey" to "odyssey",
        "odyssey-2" to "odyssey2",
        "odyssey-2-slash-videopac-g7000" to "odyssey2",
        "ohio-scientific" to "ohio-scientific",
        "onlive-game-system" to "onlive-game-system",
        "ooparts" to "ooparts",
        "openbor" to "openbor",
        "orao" to "orao",
        "oric" to "oric",
        "os2" to "os2",
        "ouya" to "ouya",
        "palm-os" to "palm",
        "palmtex" to "palmtex",
        "panasonic-jungle" to "panasonic-jungle",
        "panasonic-m2" to "panasonic-m2",
        "pandora" to "pandora",
        "pc-50x-family" to "pc-50x-family",
        "pc-6001" to "pc-6001",
        "pc-8000" to "pc-8000",
        "pc-8800-series" to "pc88",
        "pc-9800-series" to "pc98",
        "pc-booter" to "pc-booter",
        "pc-fx" to "pcfx",
        "pc-jr" to "pc-jr",
        "pdp-7" to "pdp-7",
        "pdp-8" to "pdp-8",
        "pdp1" to "pdp1",
        "pdp10" to "pdp10",
        "pdp11" to "pdp11",
        "pebble" to "pebble",
        "pegasus" to "pegasus",
        "philips-cd-i" to "cdimono1",
        "philips-vg-5000" to "philips-vg-5000",
        "photocd" to "photocd",
        "pico" to "pico8",
        "pinball" to "pinball",
        "pippin" to "pippin",
        "plato" to "plato",
        "playdate" to "playdate",
        "playdia" to "playdia",
        "playstation-now" to "playstation-now",
        "plex-arcade" to "plex-arcade",
        "plug-and-play" to "plug-and-play",
        "pocket-challenge-v2" to "pocket-challenge-v2",
        "pocket-challenge-w" to "pocket-challenge-w",
        "pocketstation" to "pocketstation",
        "pokemon-mini" to "pokemini",
        "pokitto" to "pokitto",
        "poly-88" to "poly-88",
        "polymega" to "polymega",
        "ps2" to "ps2",
        "ps3" to "ps3",
        "ps4" to "ps4",
        "ps5" to "ps5",
        "psp" to "psp",
        "psp-minis" to "psp",
        "psvita" to "psvita",
        "psvr" to "psvr",
        "psvr2" to "psvr2",
        "psx" to "psx",
        "r-zone" to "r-zone",
        "rca-studio-ii" to "rca-studio-ii",
        "research-machines-380z" to "research-machines-380z",
        "roku" to "roku",
        "sam-coupe" to "samcoupe",
        "satellaview" to "satellaview",
        "saturn" to "saturn",
        "sc3000" to "sc3000",
        "scmp" to "scmp",
        "scummvm" to "scummvm",
        "sd-200270290" to "sd-200270290",
        "sdssigma7" to "sdssigma7",
        "sega-pico" to "sega-pico",
        "sega32" to "sega32xna",
        "segacd" to "segacd",
        "segacd32" to "sega32xna",
        "series-x-s" to "series-x-s",
        "sfam" to "sfc",
        "sg1000" to "sg-1000",
        "sharp-mz-2200" to "sharp-mz-2200",
        "sharp-mz-80b20002500" to "sharp-mz-80b20002500",
        "sharp-mz-80k7008001500" to "sharp-mz-80k7008001500",
        "sharp-x68000" to "x68000",
        "sharp-zaurus" to "sharp-zaurus",
        "signetics-2650" to "signetics-2650",
        "sinclair-ql" to "sinclair-ql",
        "sk-vm" to "sk-vm",
        "smc-777" to "smc-777",
        "sms" to "mastersystem",
        "snes" to "snes",
        "socrates" to "socrates",
        "sol-20" to "sol-20",
        "sord-m5" to "sord-m5",
        "spectravideo" to "spectravideo",
        "sri-5001000" to "sri-5001000",
        "stadia" to "stadia",
        "steam-vr" to "steam-vr",
        "stv" to "stv",
        "sufami-turbo" to "sufami",
        "super-acan" to "supracan",
        "super-nes-cd-rom-system" to "snes",
        "super-vision-8000" to "super-vision-8000",
        "supergrafx" to "supergrafx",
        "supervision" to "supervision",
        "sure-shot-hd" to "sure-shot-hd",
        "swancrystal" to "wonderswancolor",
        "switch" to "switch",
        "switch-2" to "switch-2",
        "swtpc-6800" to "swtpc-6800",
        "symbian" to "symbian",
        "system-32" to "system-32",
        "system16" to "system16",
        "system32" to "system32",
        "tads" to "tads",
        "taito-x-55" to "type-x",
        "tandy-vis" to "tandy-vis",
        "tatung-einstein" to "tatung-einstein",
        "tektronix-4050" to "tektronix-4050",
        "tele-spiel" to "tele-spiel",
        "telstar-arcade" to "telstar-arcade",
        "terebikko-slash-see-n-say-video-phone" to "terebikko-slash-see-n-say-video-phone",
        "terminal" to "terminal",
        "turbografx16--1" to "tg16",
        "thomson-mo5" to "moto",
        "thomson-to" to "to8",
        "ti-82" to "ti-82",
        "ti-83" to "ti-83",
        "ti-99" to "ti99",
        "ti-994a" to "ti-994a",
        "ti-programmable-calculator" to "ti-programmable-calculator",
        "tiki-100" to "tiki-100",
        "tim" to "tim",
        "timex-sinclair-2068" to "timex-sinclair-2068",
        "tizen" to "tizen",
        "tomahawk-f1" to "tomahawk-f1",
        "tomy-tutor" to "tomy-tutor",
        "tomy-tutor-slash-pyuta-slash-grandstand-tutor" to "tomy-tutor-slash-pyuta-slash-grandstand-tutor",
        "triton" to "triton",
        "trs-80" to "trs-80",
        "trs-80-color-computer" to "trs-80",
        "trs-80-mc-10" to "trs-80",
        "trs-80-model-100" to "trs-80",
        "turbografx-cd" to "tg-cd",
        "tvos" to "tvos",
        "type-x" to "type-x",
        "uzebox" to "uzebox",
        "vc" to "vc",
        "vc-4000" to "vc-4000",
        "06c" to "06c",
        "vectrex" to "vectrex",
        "versatile" to "versatile",
        "vflash" to "vflash",
        "vic-20" to "vic20",
        "videobrain" to "videobrain",
        "videopac-g7400" to "videopac",
        "virtualboy" to "virtualboy",
        "vis" to "vis",
        "visionos" to "visionos",
        "visual-memory-unit-slash-visual-memory-system" to "visual-memory-unit-slash-visual-memory-system",
        "vmu" to "vmu",
        "vsmile" to "vsmile",
        "wang2200" to "wang2200",
        "wasm-4" to "wasm4",
        "watchos" to "watchos",
        "webos" to "webos",
        "wii" to "wii",
        "wiiu" to "wiiu",
        "win" to "windows",
        "win3x" to "windows3x",
        "windows-apps" to "windows",
        "windows-mixed-reality" to "windows-mixed-reality",
        "windows-mobile" to "windows-mobile",
        "winphone" to "winphone",
        "wipi" to "wipi",
        "wonderswan" to "wonderswan",
        "wonderswan-color" to "wonderswancolor",
        "x1" to "x1",
        "xavixport" to "xavixport",
        "xbox" to "xbox",
        "xbox360" to "xbox360",
        "xboxcloudgaming" to "xboxcloudgaming",
        "xboxone" to "xboxone",
        "xerox-alto" to "xerox-alto",
        "z-machine" to "zmachine",
        "z80" to "z80",
        "z88" to "z88",
        "zeebo" to "zeebo",
        "zilog-z8000" to "zilog-z8000",
        "zinc" to "zinc",
        "zod" to "zod",
        "zodiac" to "zodiac",
        "zune" to "zune",
        "zx-spectrum-next" to "zxnext",
        "zx80" to "zx80",
        "zx81" to "zx81",
        "zxs" to "zxspectrum"
    )

    /**
     * Get the ES-DE folder name for a given RomM platform slug
     * @param rommSlug The RomM platform slug
     * @return The ES-DE folder name, or the original slug if no mapping exists
     */
    fun getEsdeFolderName(rommSlug: String): String {
        return rommToEsdeMapping[rommSlug] ?: rommSlug
    }

    /**
     * Check if a mapping exists for the given RomM platform slug
     * @param rommSlug The RomM platform slug
     * @return True if mapping exists, false otherwise
     */
    fun hasMappingFor(rommSlug: String): Boolean {
        return rommToEsdeMapping.containsKey(rommSlug)
    }

    /**
     * Get all supported RomM platform slugs
     * @return Set of all RomM platform slugs that have ES-DE mappings
     */
    fun getSupportedRommSlugs(): Set<String> {
        return rommToEsdeMapping.keys
    }

    /**
     * Get all ES-DE folder names
     * @return Set of all ES-DE folder names
     */
    fun getEsdeFolderNames(): Set<String> {
        return rommToEsdeMapping.values.toSet()
    }

    /**
     * Reverse lookup: Get RomM platform slug from ES-DE folder name
     * @param esdeFolderName The ES-DE folder name
     * @return The RomM platform slug, or the original folder name if no mapping exists
     */
    fun getRommSlugFromEsdeFolder(esdeFolderName: String): String {
        return rommToEsdeMapping.entries.find { it.value == esdeFolderName }?.key ?: esdeFolderName
    }
}
